# stack yaml for ghc builds

resolver: lts-13.24

extra-deps:
  # --- Missing from Stackage --- #
  - ed25519-donna-0.1.1
  - prettyprinter-convert-ansi-wl-pprint-1.1

  # --- Forced Downgrades --- #

  # --- Forced Upgrades --- #
  - sbv-8.2

  # --- Custom Pins --- #
  - git: https://github.com/kadena-io/thyme.git
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9

  # pre-release of hedgehog because we need de401e9 for its relaxed typeclass
  # constraint:
  - git: https://github.com/hedgehogqa/haskell-hedgehog.git
    commit: 921e4af72a181f01d90816fd7055b823bf885b3b
    subdirs:
      - hedgehog