# stack yaml for ghc builds

resolver: lts-14.4

extra-deps:
  # --- Missing from Stackage --- #
  - ed25519-donna-0.1.1

  # --- Forced Downgrades --- #
  - hedgehog-0.6.1
  - megaparsec-6.5.0
  - neat-interpolation-0.3.2.2  # Due to megaparsec 7
  - sbv-8.2
  - swagger2-2.3.1.1

  # --- Custom Pins --- #
  - git: https://github.com/kadena-io/thyme.git
    commit: 6ee9fcb026ebdb49b810802a981d166680d867c9
